# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.5"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Centos7"
    vb.memory = "2048"
    vb.cpus = "2"
    vb.customize ["setextradata", :id, "VBoxAuthSimple/users/dev", "1"]
  end

  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
end